[project]
name = "flix-http"
version = "0.1.0"
flix = "0.32.1"
description = "The beginnings of a Flix HTTP server"
paths = ["src"]

[dependencies]
mvn."org.eclipse.jetty:jetty-server" = "11.0.12"
mvn."org.slf4j:slf4j-simple" = "2.0.3"
